version: "3.8"
services:
    pyserver:  # this name corresponds with the `proxy_pass http://pyserver:81;` in nginx/default.conf
        build:
            context: /app
        ports:
            - "81:81"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "82:82"