# Use Alpine Linux as the base image
FROM alpine:latest

# Set the working directory
WORKDIR /app

# Install Python and pip
RUN apk update && \
    apk add --no-cache python3 py3-pip

# Copy the requirements file into the container
COPY requirements.txt .

# Install dependencies from the requirements file
RUN pip3 install --no-cache-dir -r requirements.txt

# Copy the Gunicorn configuration file
COPY gunicorn_config.py .

# Copy the application code into the container
COPY . .

# Install nginx
RUN apk add --no-cache nginx

# Copy the nginx configuration file to /etc/nginx/
COPY nginx.conf /etc/nginx/nginx.conf

# Start Gunicorn and Nginx
CMD gunicorn app:app -c gunicorn_config.py & \
    nginx -g 'daemon off;'

# Expose the necessary ports
EXPOSE 80 443
